title: VIXILE Studios
description: >-
  This is the blog page for the VIXILE Studios game development team.
permalink: /:title
baseurl: "/blog"
url: "https://vixilestudios.github.io/blog"

theme: minima
plugins:
  - jekyll-feed

paginate: 5
paginate_path: "/page:num"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/