title: VIXILE Studios
description: >-
  Find news about VIXILE Studios here!
permalink: /:title
baseurl: ""
url: "https://vixilestudios.github.io/blog"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5
paginate_path: "/page:num"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
