title: VIXILE Studios
description: >- # this means to ignore newlines until "baseurl:"
  This is the blog page for the VIXILE Studios game development team.
permalink: /:title
url: "vixilestudios.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Pagination settings
paginate: 5 # Number of posts per page for pagination
paginate_path: "/page:num/" # Pagination path for blog posts

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom variables
# You can define custom variables to be used in your templates
# For example:
# my_custom_variable: "This is my custom variable"
