backend:
  name: github
  repo: vixilestudios/blog
  branch: main
  base_url: https://auth.vixile.workers.dev

media_folder: "/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post", comment: "this should be ~5 words" }
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Short Description", name: "excerpt", widget: "text", comment: "this should be around 50 characters or less" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm [+0200]" }
      - { label: "Tag", pattern: ['^[a-z0-9]+$', "Must be lowercase letters and numbers only, no spaces."], comment: "The tag should usually be the blog topic, make sure your tag is something simple and possibly consistent", name: "categories", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Content", comment: "do not remove the default markdown, unless you don't want the image to show up on the top of the blog content", name: "body", widget: "markdown", default: "<img class=\"page-image\" src=\"{{ site.url }}/{{ page.image }}\" alt=\"{{ page.excerpt }}\">" }
